[PDI-17853] - Need support to connect with MongoDB Atlas using latest…
pentaho/pentaho-mongodb-plugin pull request #211
Opened 2021-08-23 06:25 UTC by GopiKrishnaAngadi

… SRV connection string

2021-08-23 06:29 UTC, buildguy commented
### :x: Build failed in 3m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl pentaho-mongodb-plugin
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2021-08-23 15:24 UTC, peterrinehart requested changes
Looks good overall, but the following changes are necessary:
1) Ensure any existing code files get the copyright dates updated in the header so that the final year listed is 2021.
2) Some of those Sonar code smells should be corrected, such as unused fields, importing using the * operator, etc.  I understand that many of them were already present, but if fixing them doesn't take too much time or add substantial technical risk, let's get them cleaned up too.

2021-08-24 08:05 UTC, buildguy commented
### :x: Build failed in 6m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl pentaho-mongodb-plugin
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2021-08-24 11:01 UTC, buildguy commented
### :x: Build failed in 3m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl pentaho-mongodb-plugin
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2021-08-24 13:45 UTC, peterrinehart requested changes
Additional license header changes and style issues need to be fixed; I've tried to call out each file still needing to have the license header updated.
Also, check the number of spaces used to indent some of these blocks; I'm not sure they're consistent with the style guidelines.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java
> +     *
If this block of commented out code isn't needed, we should delete it.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java
> +              "auth_password" ) ) ); //$NON-NLS-1$
Is this spacing consistent with the checkstyle standards?

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputDiscoverFields.java
> +  List<MongoField> discoverFields( MongoProperties.Builder properties, String db, String collection,
This file does not appear to have a valid license header.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputData.java
> + * Copyright 2010 - 2021 Hitachi Vantara.  All rights reserved.
If we didn't change anything else in this file, we don't need to update the license header.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java
> +    //props.setLook( m_wTabFolder, Props.WIDGET_STYLE_TAB );
This commented line can be deleted.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java
> +            BaseMessages.getString( PKG, "MongoDbInputDialog.TestUserTags.Button.TipText" ) ); //$NON-NLS-1$
Is this spacing consistent with style guidelines?

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/mongo/wrapper/MongoWrapperClientFactory.java
> +
This file appears to be missing its license header.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/main/java/org/pentaho/mongo/wrapper/field/MongodbInputDiscoverFieldsImpl.java
> +import org.pentaho.di.core.variables.VariableSpace;
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputDataTest.java
> +import org.mockito.Matchers;
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMetaInjectionTest.java
> +    check( "USE_CONNECTION_STRING", new BooleanGetter() {
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMetaTest.java
> +            return "{" + UUID.randomUUID() + "}";
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMetaInjectionTest.java
> +    check( "USE_CONNECTION_STRING", new BooleanGetter() {
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputTest.java
> +    newMeta.loadXML( stepNode, null, (IMetaStore) null );
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/mongo/wrapper/MongoWrapperUtilTest.java
> +import org.junit.runner.RunWith;
This file needs the copyright date updated.

2021-08-24 13:45 UTC, peterrinehart commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/mongo/wrapper/field/MongodbInputDiscoverFieldsImplTest.java
> +import org.pentaho.di.core.variables.VariableSpace;
This file needs the copyright date updated.

2021-08-24 16:43 UTC, buildguy commented
### :x: Build failed in 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl pentaho-mongodb-plugin
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

2021-08-24 17:15 UTC, merged