[BACKLOG-39576] JDK17 update, move to modern Mockito version
pentaho/pentaho-mongodb-plugin pull request #232
Opened 2024-03-06 21:30 UTC by pentaho-whartman

2024-03-06 21:39 UTC, peterrinehart requested changes

2024-03-07 14:52 UTC, pentaho-whartman commented on pentaho-mongodb-plugin/logs/pdi.log
I think this gets generated by the tests. Removing it and adding it to the gitignore

2024-03-07 14:52 UTC, pentaho-whartman commented on pentaho-mongodb-plugin/src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDataTest.java
>  import static org.junit.Assert.*;
👍 Looks like there's more in other classes too -- Running the intellij import cleanup thing on all the tests.

2024-03-13 17:13 UTC, peterrinehart approved these changes

2024-03-13 17:13 UTC, merged